export const kText = {
  theWedding: "The Wedding",
  kepada: "Kepada",
  bukaUndangan: "Buka Undangan",
  atasBerkahRahmat: "Atas Berkah dan Rahmat Allah Subhanallahu Wa Ta'ala. ",
  kamiMengundang:
    "Kami mengundang Bapak/Ibu/Saudara/i ​​serta kerabat sekalian untuk menghadiri acara pernikahan kami :",
  ayat1:
    "وَمِنْ اٰيٰتِهٖٓ اَنْ خَلَقَ لَكُمْ مِّنْ اَنْفُسِكُمْ اَزْوَاجًا لِّتَسْكُنُوْٓا اِلَيْهَا وَجَعَلَ بَيْنَكُمْ مَّوَدَّةً وَّرَحْمَةً ۗاِنَّ فِيْ ذٰلِكَ لَاٰيٰتٍ لِّقَوْمٍ يَّتَفَكَّرُوْنَ",
  ayat1Arti: `"Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir."`,
  ayat1Surat: "(QS Ar-Rum: 21)",
  saveTheDate: "Save The Date",
  pukul: "Pukul",
  mapLokasiAcara: "Map Lokasi Acara",
  merupakanSuatuKehormatan:
    "Merupakan suatu kehormatan dan kebahagiaan bagi kami sekeluarga, apabila Bapak/Ibu/Saudara/i ​​berkenan hadir dan memberikan doa restu. ",
  memberikanDoaRestu:
    "memberikan doa restu. Atas kehadiran dan doa restunya, kami mengucapkan terima kasih.",
  linkMaps: "https://maps.app.goo.gl/ZsafwexTP5KwTCr3A",
  acaraAkad: "Acara Akad",
  hariAcaraAkad: "Minggu, 15 Oktober 2023",
  waktuAcaraAkad: "09.00 - 09.30 WIB",
  tempatAcaraAkad: "Gedung Serbaguna Kalitirto",
  acaraResepsi: "Acara Resepsi",
  hariAcaraResepsi: "Minggu, 15 Oktober 2023",
  waktuAcaraResepsi: "09.00 - 09.30 WIB",
  tempatAcaraResepsi: "Gedung Serbaguna Kalitirto",
  kehadiran: "Kehadiran",
  nama: "Nama",
  ucapan: "Ucapan",
  kirim: "Kirim",
  hadir: "Hadir",
  tidakHadir: "Tidak Hadir",
  totalUcapan: "Total Ucapan",
  orangMenyatakanHadir: "Orang Menyatakan Hadir",
  ourGallery: "Our Gallery",
  terimaKasih: "Terimakasih",
  merupakanSuatuKebahagiaan:
    "Merupakan Suatu Kebahagiaan dan Kehormatan bagi Kami, Apabila Bapak/Ibu/Saudara/i, Berkenan Hadir di Acara kami",
  instagramId: "abd.harits19",
};
