name: cd

on:
  push:
    branches:
      - disabled

jobs:
  cd:
    runs-on: ubuntu-latest
    environment: SSH
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 34.101.54.54
          username: harits
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p ~/app/invitation-frontend
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/app/invitation-frontend
            echo yes | git clone git@github.com:Harits19/wedding-invitation-app-react.git .
            git remote add origin git@github.com:Harits19/wedding-invitation-app-react.git
            git branch --set-upstream-to=origin/master master
            git config --global user.email "harits.abdullah19@gmail.com"
            git config --global user.name "Harits"
            git config pull.rebase false
            git pull origin master
            git status
            npm install
            npm run build
            jobs
            kill %1
            jobs
            npm run start >"debug_$(date).log" &
            sudo ufw allow 8080
