name: cd

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    environment: SSH
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 38.47.180.46
          username: root
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p ~/app/invitation-frontend
            cd ~/app/invitation-frontend
            git init
            git clone https://github.com/Harits19/wedding-invitation-app-react.git .
            git remote add origin https://github.com/Harits19/wedding-invitation-app-react.git
            git branch --set-upstream-to=origin/master master
            git pull origin master
            git status
            # npm run build
            # kill $(lsof -t -i:3000)
            # npm run start & npx wait-on http://localhost:3000
